/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/avatar.vue')['default']
    Badge: typeof import('./src/components/ui/badge.vue')['default']
    Button: typeof import('./src/components/ui/button.vue')['default']
    Card: typeof import('./src/components/ui/card.vue')['default']
    CardContent: typeof import('./src/components/ui/card-content.vue')['default']
    CardDescription: typeof import('./src/components/ui/card-description.vue')['default']
    CardFooter: typeof import('./src/components/ui/card-footer.vue')['default']
    CardHeader: typeof import('./src/components/ui/card-header.vue')['default']
    CardTitle: typeof import('./src/components/ui/card-title.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog-content.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog-description.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog-footer.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog-header.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog-title.vue')['default']
    DropdownMenu: typeof import('./src/components/ui/dropdown-menu.vue')['default']
    DropdownMenuItem: typeof import('./src/components/ui/dropdown-menu-item.vue')['default']
    DropdownMenuLabel: typeof import('./src/components/ui/dropdown-menu-label.vue')['default']
    DropdownMenuSeparator: typeof import('./src/components/ui/dropdown-menu-separator.vue')['default']
    Input: typeof import('./src/components/ui/input.vue')['default']
    Loading: typeof import('./src/components/ui/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/ui/table.vue')['default']
    TableBody: typeof import('./src/components/ui/table-body.vue')['default']
    TableCell: typeof import('./src/components/ui/table-cell.vue')['default']
    TableHead: typeof import('./src/components/ui/table-head.vue')['default']
    TableHeader: typeof import('./src/components/ui/table-header.vue')['default']
    TableRow: typeof import('./src/components/ui/table-row.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip.vue')['default']
  }
}
