# 向量处理和缓存配置
vector:
  # 缓存配置
  cache:
    enabled: true
    default-ttl: 24h
    max-memory-usage: 512MB

    # Redis缓存配置
    redis:
      key-prefix: "deepsearch:vector:"
      compression: true
      serialization: json

    # 缓存策略
    strategy:
      # LRU: 最近最少使用
      # LFU: 最少使用频率
      # TTL: 基于时间过期
      eviction-policy: LRU
      max-entries: 50000

  # 文本预处理配置
  preprocessing:
    max-chunk-size: 512
    chunk-overlap: 50
    min-chunk-size: 50
    remove-stop-words: false

    # 清理选项
    remove-html: true
    remove-urls: true
    remove-emails: true
    normalize-whitespace: true

  # 质量评估配置
  quality:
    min-magnitude: 0.1
    max-magnitude: 10.0
    similarity-threshold: 0.95
    variance-threshold: 0.001

    # 质量检查选项
    check-nan-values: true
    check-infinite-values: true
    check-zero-variance: true
    check-outliers: true

  # 性能优化配置
  optimization:
    # 向量压缩
    compression:
      enabled: false
      target-dimension: 256
      precision: 8

    # 批处理配置
    batch:
      size: 100
      parallel: true
      max-concurrent: 10

    # 内存管理
    memory:
      max-heap-usage: 80%
      gc-threshold: 70%

  # 监控和指标
  monitoring:
    enabled: true
    metrics-interval: 60s

    # 性能指标
    track-cache-stats: true
    track-processing-time: true
    track-quality-scores: true
    track-memory-usage: true

# Spring Data Redis配置
spring:
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 2000ms

    # 连接池配置
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 2
        max-wait: 2000ms

    # Redis集群配置（如果使用集群）
    # cluster:
    #   nodes:
    #     - localhost:7000
    #     - localhost:7001
    #     - localhost:7002
    #   max-redirects: 3

    # Redis哨兵配置（如果使用哨兵）
    # sentinel:
    #   master: mymaster
    #   nodes:
    #     - localhost:26379
    #     - localhost:26380
    #     - localhost:26381

# Jackson JSON配置
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-durations-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      accept-empty-string-as-null-object: true
    default-property-inclusion: non_null

# 日志配置
logging:
  level:
    com.deepsearch.vector: DEBUG
    org.springframework.data.redis: WARN
    io.lettuce.core: WARN

# Actuator监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,vectorcache
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: deep-search
      component: vector-processing